module.exports = function () {
  return {
    user: [
      {
        id: "1",
        user_id: "1",
        name: "Harshita",
        email: "harshita@example.com",
        userGroups: ["101", "102", "105"],
      },
      {
        id: "2",
        user_id: "2",
        name: "Rohan",
        email: "rohan@example.com",
        userGroups: ["101", "103", "104"],
      },
      {
        id: "3",
        user_id: "3",
        name: "Sneha",
        email: "sneha@example.com",
        userGroups: ["101", "103", "104", "105"],
      },
      {
        id: "4",
        user_id: "4",
        name: "Arjun",
        email: "arjun@example.com",
        userGroups: ["101", "102", "104"],
      },
      {
        id: "5",
        user_id: "5",
        name: "Priya",
        email: "priya@example.com",
        userGroups: ["101", "102", "103", "105"],
      },
    ],
    groups: [
      {
        id: "101",
        group_id: "101",
        group_name: "Goa Trip",
        description: "mazze aarahe hai",
        category: "Travel",
        created_by: "1",
        members: ["1", "2", "3", "4", "5"],
        expenses: ["501", "502", "503"],
      },
      {
        id: "102",
        group_id: "102",
        group_name: "Office Party",
        description: "mazze aarahe hai",
        category: "Party",
        created_by: "4",
        members: ["1", "4", "5"],
        expenses: ["504", "505"],
      },
      {
        id: "103",
        group_id: "103",
        group_name: "Birthday Bash",
        description: "mazze aarahe hai",
        category: "Party",
        created_by: "5",
        members: ["2", "3", "5"],
        expenses: ["506"],
      },
      {
        id: "104",
        group_id: "104",
        group_name: "Weekend Getaway",
        description: "mazze aarahe hai",
        category: "Travel",
        created_by: "2",
        members: ["2", "3", "4"],
        expenses: ["507", "508", "509"],
      },
      {
        id: "105",
        group_id: "105",
        group_name: "Flatmates",
        description: "mazze aarahe hai",
        category: "Grocery",
        created_by: "3",
        members: ["1", "3", "5"],
        expenses: ["510", "511"],
      },
    ],

    expenses: [
      {
        expense_id: "501",
        group_id: "101",
        description: "Hotel Booking",
        amount: 6000,
        paid_by: "1",
        date: "2025-08-15",
        users: ["2", "3"],
      },

      {
        expense_id: "502",
        group_id: "101",
        description: "Dinner at Beach Shack",
        amount: 2400,
        paid_by: "2",
        date: "2025-08-16",
        users: ["1", "3"],
      },

      {
        expense_id: "503",
        group_id: "101",
        description: "Scooter Rental",
        amount: 1500,
        paid_by: "3",
        date: "2025-08-17",
        users: ["3", "4", "5"],
      },

      {
        expense_id: "504",
        group_id: "102",
        description: "Snacks & Drinks",
        amount: 1800,
        paid_by: "4",
        date: "2025-07-10",
        users: ["1", "5"],
      },

      {
        expense_id: "505",
        group_id: "102",
        description: "Decorations",
        amount: 1200,
        paid_by: "4",
        date: "2025-07-11",
        users: ["4", "5"],
      },

      {
        expense_id: "506",
        group_id: "103",
        description: "Cake & Gifts",
        amount: 3000,
        paid_by: "5",
        date: "2025-06-20",
        users: ["2", "3", "5"],
      },

      {
        expense_id: "507",
        group_id: "104",
        description: "Trip to Mysore",
        amount: 7000,
        paid_by: "4",
        date: "2025-06-20",
        users: ["2", "3"],
      },
      {
        expense_id: "508",
        group_id: "104",
        description: "Grocery Shopping",
        amount: 1000,
        paid_by: "4",
        date: "2025-06-20",
        users: ["3", "4"],
      },

      {
        expense_id: "509",
        group_id: "104",
        description: "Shipping",
        amount: 5000,
        paid_by: "3",
        date: "2025-06-20",
        users: ["2", "4"],
      },
      {
        expense_id: "510",
        group_id: "105",
        description: "Trip to Mumbai",
        amount: 1000,
        paid_by: "1",
        date: "2025-06-20",
        users: ["3", "5"],
      },
      {
        expense_id: "511",
        group_id: "105",
        description: "Seoul",
        amount: 10000,
        paid_by: "3",
        date: "2025-06-20",
        users: ["1", "3", "5"],
      },
    ],
  };
};
